#!/bin/bash

# for use with pre-Senegal format research releases in an existing MongoDB

# does NOT standardize data
# does NOT load data into a mongo database
# does NOT update form_data.json

# takes country name as input
# country name must match existing mongo database name

# example use:
# bash /var/www/html/aiddata/data/form/runMongo_presenegal Nepal

country=$1

sectors=('Agriculture' 'Education' 'Health' 'Industry' 'Water' 'Other')

base='/var/www/html/aiddata/data/form/'

for i in "${sectors[@]}"

do

	# # create csv using new mongo db/collection and build vrt
	/usr/bin/php5 $base'buildCSV_presenegal.php' $country $i

	# # remove geojson if it exists (ogr will not overwrite)
	if [[ -e $base'sector_data/'$country'_'$i'.geojson' ]]
		then
			rm $base'sector_data/'$country'_'$i'.geojson'
	fi

	# # create geojson using vrt
	ogr2ogr -f GeoJSON $base'sector_data/'$country'_'$i'.geojson' $base'sector_data/'$country'_'$i'.vrt'


	# # run PET extract with geojson for each raster
	python '/var/www/html/aiddata/PET/extract.py' 'vector' $base'sector_data/'$country'_'$i'.geojson' 'project_id' 'longitude' 'latitude' '/var/www/html/aiddata/DET/uploads/globals/processed/agriculture__actual_potential_yield_gap__2000/gap2000_gap_2000_hi_cl.tif' $base'extract_data/'$country'_'$i'_Yield.csv' 'agriculture__actual_potential_yield_gap__2000' 'total_commitments,location_count'
	python '/var/www/html/aiddata/PET/extract.py' 'vector' $base'sector_data/'$country'_'$i'.geojson' 'project_id' 'longitude' 'latitude' '/var/www/html/aiddata/DET/uploads/globals/processed/socioeconomics__local_economic_activity__1995/nord_gcgpp05.tif' $base'extract_data/'$country'_'$i'_Income.csv' 'socioeconomics__local_economic_activity__1995' 'total_commitments,location_count'
	python '/var/www/html/aiddata/PET/extract.py' 'vector' $base'sector_data/'$country'_'$i'.geojson' 'project_id' 'longitude' 'latitude' '/var/www/html/aiddata/DET/uploads/globals/processed/socioeconomics__urban_areas__1995/glurextents.asc' $base'extract_data/'$country'_'$i'_Urban.csv' 'socioeconomics__urban_areas__1995' 'total_commitments,location_count'

	# # join results to $base'extract_data/'$country'_'$i'.csv'
	/usr/bin/php5 $base'joinExtract.php' $country $i

	# check if country / sector is in buildJSON
	# replace if it exists
	# add if it does not exist
	new_line="python /var/www/html/aiddata/data/form/calc.py /var/www/html/aiddata/data/form/form_data/"$country"_"$i".csv $i $country total_commitments location_count"
	FILE=$base'buildJSON'
	same="0"
	while read line
	do
		if [[ $line = $new_line  ]]
		then
			same="1"
		fi
	done < $FILE

	if [[ $same = "0" ]]
	then
		echo -e $new_line >> $base'buildJSON'

	fi

done

bash $base'buildJSON'


echo 'done'
echo -e '\n'
